import MongooseSetup from "./lib/MongooseSetup.js";
import dotenv from "dotenv";
import Card from "./models/Card.js"; // Update this path

dotenv.config();

MongooseSetup();

const questions = [
    "Why can't I sleep at night? [blank]",
    "I got 99 problems but [blank] ain't one.",
    "What ended my last relationship? [blank]",
    "What helps Obama unwind? [blank]",
    "What's that sound? [blank]",
    "What's a girl's best friend? [blank]",
    "What's my secret power? [blank]",
    "What's the new diet? [blank]",
    "What will always get you laid? [blank]",
    "What's the most emo? [blank]",
    "What are my parents hiding from me? [blank]",
    "What never fails to liven up the party? [blank]",
    "What's the new fad diet? [blank]",
    "What's Batman's guilty pleasure? [blank]",
    "Why am I sticky? [blank]",
    "What would grandma find disturbing, yet oddly charming? [blank]",
    "What's the cringiest? [blank]",
    "What's the most controversial opinion I have? [blank]",
    "What's the worst thing to say during a job interview? [blank]",
    "The school cafeteria now serves [blank] with a side of [blank].",
    "A wild night out always includes [blank] and [blank] in that order.",
    "During my first year of college, I discovered [blank] and [blank] go well together.",
    "What's the weirdest thing you can buy at the college bookstore? [blank]",
    "Campus rumors say the real reason for the network downtime was [blank].",
    "The secret ingredient in the dining hall's mystery meat is [blank].",
    "What's the real reason the campus statue was vandalized? [blank]",
    "The only way to survive a night in the library is with [blank] and [blank].",
    "My plan for world domination begins with [blank].",
    "Underneath the gym's floorboards, we found [blank] and [blank].",
    "What's the title of the mandatory freshman seminar? 'The Art of [blank]'",
    "What's the one thing I can always find in my backpack? [blank]",
    "The most unexpected thing learned in Gender Studies: [blank]",
    "What's the actual reason for the Wi-Fi outage? Hint: It involves [blank].",
    "What did I find in my roommate's drawer? [blank]",
    "The theme for next year's homecoming: [blank] and [blank].",
    "What's the real reason the fire alarm went off at 3 AM? [blank]",
    "The most bizarre elective offered: Underwater [blank]",
    "The one class everyone sleeps through: [blank] 101.",
    "What's the hottest campus gossip? [blank] and [blank] were caught in [blank].",
    "Our RA banned [blank] after the incident with [blank].",
    "What's the weirdest club on campus? The [blank] Club.",
    "What's the one thing that will always start a debate in class? [blank]",
    "The most memorable part of orientation was [blank].",
    "The one book everyone pretends to have read: [blank]",
    "What's the real reason behind my procrastination? [blank] and [blank].",
    "Why do I have a bad feeling about this? [blank], [blank], and [blank].",
    "What's the newest viral challenge? The [blank] Challenge.",
    "The secret to acing finals: [blank] and [blank].",
    "What's the theme of the underground campus party? [blank] Night.",
    "What's the most bizarre study tip I've received? 'Try studying while [blank].'",
    "The one thing that unites all students: [blank]",
    "What's the latest campus fashion trend? [blank] with [blank]",
    "The most unexpected guest at the career fair: A recruiter for [blank]",
    "What's the one thing you shouldn't bring to the dorms? [blank]",
    "The best way to make a professor laugh: [blank]",
    "What's the worst group project experience? Being paired with [blank]",
    "What's the best way to stay warm during winter semesters? [blank]",
    "The college's unofficial mascot: [blank]",
    "Why is the campus café always out of [blank]?",
    "What's the best way to make a new friend? [blank]",
    "The real reason everyone chooses this college: [blank]",
    "What will I bring to the next student council meeting? [blank] and [blank]",
    "What's the weirdest minor you can declare? [blank] Studies.",
    "The best place to take a nap on campus: [blank]",
    "The most unforgettable moment of the semester: [blank]",
    "The biggest myth about college life: [blank]",
    "What's the one thing we all did during online classes? [blank]",
    "The most creative way to cheat on an exam: [blank]",
    "What's the best part of college? [blank] and [blank]",
    "The most absurd college course: The Philosophy of [blank]",
    "The real reason for joining a fraternity/sorority: [blank]",
    "The one thing that can always distract me from studying: [blank]",
    "Why am I in debt? [blank] and [blank]",
    "The most unexpected thing to bring to a tailgate: [blank]",
    "What's the real tradition during finals week? [blank]",
    "The one thing that always happens during spring break: [blank]",
    "The college's best kept secret: [blank]",
    "The most interesting find during a campus cleanup: [blank]",
    "What's the official snack of late-night study sessions? [blank]",
    "The weirdest thing a professor ever did in class: [blank]",
    "The one thing that's worth attending a lecture for: [blank]",
    "What's the most absurd thing overheard on campus? [blank]",
    "The real reason the campus Wi-Fi is so slow: [blank]",
    "The most unexpected club activity: Competitive [blank]",
    "The one thing freshmen need to learn: [blank]",
    "The most bizarre reason for a class cancellation: [blank]",
    "The most memorable campus event: The Great [blank] Escape.",
    "The most unexpected item in the lost and found: [blank]",
    "The one thing you don't expect to find in the library: [blank]",
    "The real reason we all chose this major: [blank]",
    "The most surprising thing about college friendships: [blank]",
    "The one thing that truly tests a dorm's friendship: [blank]",
    "The most creative excuse for missing a deadline: [blank]",
    "The most unexpected collaboration: The Math Club and [blank]",
    "The one thing every student complains about: [blank]",
    "The best discovery made on campus: [blank]",
    "The most unusual campus tradition involves [blank] and [blank]",
    "The one thing that makes any class better: [blank]",
    "The biggest surprise in the student handbook: [blank]",
    "The most creative club fundraiser: Sell [blank] for [blank]",
    "The most unexpected lecture topic: The History of [blank]",
    "The most bizarre thing to decorate a dorm with: [blank]",
    "The real reason for the rivalry with the neighboring college: [blank]",
    "The one thing that can unite all majors: [blank]",
    "The most unexpected place to find peace on campus: [blank]",
    "The biggest challenge of college life: [blank] and [blank]",
    "The one piece of advice every senior gives: Always remember [blank]",
    "The most unusual thing to major in: [blank]",
    "The one thing you never thought you'd do in college: [blank]",
    "The most unforgettable part of online learning: [blank]",
    "The weirdest college tradition: Annual [blank] Hunt."
];

const answers = [
    "Quantum homework excuses.",
    "Free pizza.",
    "Mismatched socks.",
    "Eternal Wi-Fi.",
    "Decaf coffee.",
    "Moonlight procrastination.",
    "Dorm room DJs.",
    "Silent library raves.",
    "Meme professor.",
    "Avocado toast degree.",
    "Invisible deadlines.",
    "Schrödinger's assignment.",
    "Laundry day treasure.",
    "Spontaneous naps.",
    "Mystery cafeteria meals.",
    "Group project hero.",
    "Philosophical breakdowns.",
    "Squirrel overlords.",
    "Awkward handshakes.",
    "Failed experiments.",
    "Instant ramen gourmet.",
    "Budget cosplay.",
    "Forgotten passwords.",
    "Energy drink overdose.",
    "Existential dread.",
    "Karaoke regret.",
    "Impulse travels.",
    "Vegan leather homework.",
    "Platonic crushes.",
    "Retro game marathons.",
    "Virtual reality lectures.",
    "Organic chemistry memes.",
    "Time travel thesis.",
    "Library ghost stories.",
    "Campus fashion icons.",
    "Study playlist DJ.",
    "Taco Tuesday fanatic.",
    "Unsolved math mysteries.",
    "Friendship bracelet contracts.",
    "Social media detox.",
    "Thrift store chic.",
    "Urban legend debunker.",
    "Puppy therapy.",
    "Failed magician.",
    "Hipster barista.",
    "Accidental influencer.",
    "Secret tunnel explorer.",
    "Espresso patronum.",
    "Fantasy football dropout.",
    "Noodle artistry.",
    "Sock puppet philosopher.",
    "Snowball duel champion.",
    "Unofficial mascot.",
    "Homemade rocket scientist.",
    "Duct tape tailor.",
    "Emoji poet laureate.",
    "Procrastination guru.",
    "Yoga pants connoisseur.",
    "Campus legend.",
    "Midnight snack thief.",
    "Bookstore bargain hunter.",
    "Dining hall critic.",
    "Soda can sculptor.",
    "Frisbee golf professional.",
    "Bubble wrap artist.",
    "Zombie survival planner.",
    "Password amnesiac.",
    "Coffee snob.",
    "Reality show dropout.",
    "Lawn flamingo collector.",
    "Unicycle commuter.",
    "Hopeless romantic.",
    "Sleep schedule mess.",
    "Pop culture prophet.",
    "Guacamole evangelist.",
    "Undercover genius.",
    "Jazzercise enthusiast.",
    "Pirate radio host.",
    "Cat video curator.",
    "Breakfast for dinner.",
    "Chocolate therapy.",
    "Guitar hero.",
    "Dorm room philosopher.",
    "Campfire storyteller.",
    "Space camp alumni.",
    "Arcade legend.",
    "Vintage vinyl collector.",
    "Sandcastle architect.",
    "Sidewalk chalk artist.",
    "Pizza connoisseur.",
    "Ultimate frisbee underdog.",
    "Pajama fashionista.",
    "Karate in the garage.",
    "Laser tag strategist.",
    "Corn maze navigator.",
    "Backyard astronomer.",
    "Snow angel expert.",
    "Puddle jumping champ.",
    "Fortune cookie writer.",
    "Penguin slide competitor.",
    "Ice cream taste tester.",
    "Stargazing dreamer.",
    "Sunrise chaser.",
    "Moonlight dancer.",
    "Cloud watcher.",
    "Sunset photographer.",
    "Raindrop racer.",
    "Wind whisperer.",
    "Star constellation guesser.",
    "Meteor shower party planner.",
    "Aurora borealis chaser.",
    "Eclipse enthusiast."
];

const seedData = async () => {
    await Card.deleteMany({}); // Caution: This line will delete all existing cards!

    // Create Questions
    for (const question of questions) {
        await Card.create({
            content: question,
            type: 'QUESTION',
            author: "65c3b8df2745c15a60a8f7d2",
        });
    }

    // Create Answers
    for (const answer of answers) {
        await Card.create({
            content: answer,
            type: 'ANSWER',
            author: "65c3b8df2745c15a60a8f7d2",
        });
    }

    console.log('Seed data successfully added!');

    process.exit();
};

seedData().catch(err => {
    console.error('Seed data insertion error:', err);
});
